### PR TITLE
Test version of Deployment notifications action

### PR DESCRIPTION
**Pull request by bel0v**
Action to send a message to PR when that PR's change has been deployed. 

### How it works
On a deployment:
1. get prev deployment’s sha https://docs.github.com/en/rest/reference/repos#list-deployments
2. get a list of commits since that sha https://docs.github.com/en/rest/reference/repos#list-commits
3. for each commit find a PR - https://docs.github.com/en/rest/reference/repos#list-pull-requests-associated-with-a-commit
4. send a message to that PR

### Test & Release plan

1. Run this action manually and check the logs;
2. have a separate PR to enable message send out.
3. add the workflow after `Deploy-app` on `product-web`

### CODE REVIEW

**Comment by pekala** [comment]
It's impossible to review with `node_modules` checked in :D I suggest you use something like `@vercel/ncc` to build it into a single file and check that one file in the repo, e.g. like done here https://github.com/pleo-io/frontend-infrastructure/pull/2

**Comment by bel0v** [comment]
@pekala good idea! in the meantime you can scroll down to the very end, it's a single file thing really
Screenshot 2022-01-26 at 21 35 14

**Review by pekala — APPROVED** [review]
Looks good! The new pipeline will likely mitigate the need for this action, since it will almost never fail on master (even with flaky tests, it won't re-run the tests on the default branch after the PR is merged)

**Comment by igorDolzh** [comment]
@bel0v you could test this action by realising the feature branch with tag "v.....-beta", with that I think you will be 100% that everything is okey, otherwise you maybe stuck in the loop of testing in prod -> correction, especially it is your first action

**Review by igorDolzh — COMMENTED** [review]
Waiting as @bel0v does the testing and say that everything works as expected

**Comment by bel0v** [comment]
@igorDolzh tested almost all of it, except for the message send-out function and the actual call in the [trigger-deployment workflow](https://github.com/pleo-io/product-web/pull/6303/files). 
What's the preferred way to proceed? Merge the workflow in product-web first?

**Review by igorDolzh — APPROVED** [review]

**Pull request merged**
